### ISSUE TITLE
rtbiz helpdesk v1.6.5 Plugin - Release Checklist

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/rtbiz-helpdesk#115]
We need to follow the below checklist.

- [ ] Create a manual test case sheet if not already present 
- [ ] Test Develop branch thoroughly 
- [ ] Once develop is merged to master, Test Master branch, check if new version is getting reflected
- [ ] Perform after-release steps.

**Comment by pavanpatil1** [comment]
<h3>Updated </h3>

New tag has been added https://github.com/rtCamp/rtbiz-helpdesk/releases/tag/v1.6.5 and working fine hence closing this issue.
